import React from "react";
import "../styles/Generate.css";
import { useState, useEffect } from "react";
import AutoAwesome from "@mui/icons-material/AutoAwesome";
import { GoogleGenerativeAI } from "@google/generative-ai";
import AddBoxOutlinedIcon from "@mui/icons-material/AddBoxOutlined";
import SpotifyWebApi from "spotify-web-api-js";
import axios from "axios";
import { Close } from "@mui/icons-material";
import GeneratedPlaylist from "./GeneratedPlaylist";
import HourglassEmptyIcon from "@mui/icons-material/HourglassEmpty";

export default function Generate() {
  const [preferences, setPreferences] = useState("");
  const [vibe, setVibe] = useState("");
  const [trackUri, setTrackUri] = useState([]);

  const [generatedSongs, setGeneratedSongs] = useState([]);
  const [generated, setGenerated] = useState(false);

  const [artistSearchBox, setArtistSearchBox] = useState(false);
  const [songSearchBox, setSongSearchBox] = useState(false);

  const [searchKey, setSearchKey] = useState("");

  const [artists, setArtists] = useState([]);
  const [songs, setSongs] = useState([]);
  const [artistNames, setArtistNames] = useState([]);
  const [songNames, setSongNames] = useState([]);

  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  let userId = window.localStorage.getItem("userId");

  let token = window.localStorage.getItem("token");

  const spotifyApi = new SpotifyWebApi({
    clientId: import.meta.env.VITE_SPOTIFY_ID,
    clientSecret: import.meta.env.VITE_SPOTIFY_SECRET,
    redirectUri: "http://localhost:5173/",
    scope: [
      "playlist-modify-public",
      "playlist-modify-private",
      "user-library-read",
    ].join(" "),
  });

  const params = new URLSearchParams(window.location.search);
  const code = params.get("code");

  spotifyApi.setAccessToken(token);

  async function searchTrack(trackName, artistName) {
    try {
      // Perform a search query with track name and artist name
      const searchResult = await spotifyApi.searchTracks(
        `track:${trackName} artist:${artistName}`
      );

      // If tracks were found, return the first match's URI
      if (searchResult.body.tracks.items.length > 0) {
        const track = searchResult.body.tracks.items[0];
        return track.uri; // Spotify URI for the track
      } else {
        return null;
      }
    } catch (error) {
      console.error("Error searching for track:", error);
    }
  }

  async function searchMultipleTracks(generatedSongs) {
    const trackUris = [];

    for (const generatedSong of generatedSongs) {
      const trackUri = await searchTrack(
        generatedSong.song,
        generatedSong.artist
      );
      if (trackUri) {
        trackUris.push(trackUri);
      }
    }

    return trackUris;
  }

  // Function to create a playlist
  async function createPlaylist(token, userID, playlistName, description) {
    const url = `https://api.spotify.com/v1/users/${userID}/playlists`;

    const body = JSON.stringify({
      name: playlistName,
      description: description,
      public: false, // Set to true if you want the playlist to be public
    });
    console.log("Created playlist.");
    const response = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: body,
    });

    if (!response.ok) {
      throw new Error("Failed to create playlist");
    }

    const data = await response.json();
    return data.id; // Returns the new playlist's ID
  }

  // Function to add tracks to the playlist
  async function addTracksToPlaylist(token, playlistID, trackUris) {
    const url = `https://api.spotify.com/v1/playlists/${playlistID}/tracks`;

    const body = JSON.stringify({
      uris: trackUris,
    });

    const response = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: body,
    });

    if (!response.ok) {
      throw new Error("Failed to add tracks to playlist");
    }

    console.log("Tracks added successfully to playlist:", playlistID);
  }

  // Main function to create the playlist and add tracks
  async function createPlaylistAndAddTracks(token, userID, generatedSongs) {
    try {
      // Create the playlist
      const playlistID = await createPlaylist(
        token,
        userID,
        "My Generated Playlist", // Playlist name
        "A playlist generated by my app" // Playlist description
      );

      // Search for the track URIs
      const trackUris = await searchMultipleTracks(generatedSongs);
      setTrackUri(trackUris);

      // Add the tracks to the playlist
      await addTracksToPlaylist({ token }, playlistID, trackUris);
    } catch (err) {
      console.error("Error creating playlist or adding tracks:", err);
    }
  }

  const searchArtists = async (e) => {
    let token = window.localStorage.getItem("token");
    e.preventDefault();
    try {
      const { data } = await axios.get("https://api.spotify.com/v1/search", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        params: {
          q: searchKey,
          type: "artist",
        },
      });
      setArtists(data.artists.items);
    } catch (error) {
      console.log(error.message);
      setError(true);
    }
  };

  const searchSongs = async (e) => {
    let token = window.localStorage.getItem("token");
    e.preventDefault();
    try {
      const { data } = await axios.get("https://api.spotify.com/v1/search", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
        params: {
          q: searchKey,
          type: "track",
        },
      });
      setSongs(data.tracks.items);
    } catch (error) {
      console.log(error.message);
      setError(true);
    }
  };

  const appendSongs = (songName, songArtist, songImg) => {
    setSongSearchBox(false);
    setSongNames((prevSongNames) => [
      { name: songName, artist: songArtist, image: songImg },
      ...prevSongNames,
    ]);
  };

  const deleteSongs = (songToDelete, artistToDelete, imageToDelete) => {
    setSongNames((prevSongNames) =>
      prevSongNames.filter(
        (songs) =>
          songs.name !== songToDelete ||
          songs.artist !== artistToDelete ||
          songs.image !== imageToDelete
      )
    );
  };

  const appendArtists = (artistName, artistImg) => {
    setArtistSearchBox(false);
    setArtistNames((prevArtistNames) => [
      { name: artistName, image: artistImg },
      ...prevArtistNames,
    ]);
  };

  const deleteArtist = (nameToDelete, imageToDelete) => {
    setArtistNames((prevArtistNames) =>
      prevArtistNames.filter(
        (artistName) =>
          artistName.name !== nameToDelete || artistName.image !== imageToDelete
      )
    );
  };

  const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_KEY);
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });

  async function generate() {
    setLoading(true);

    const prompt = `
  Generate a playlist of songs based on the user’s input. 
  The user is looking for this vibe: ${vibe}, which reflects the overall mood they want. 
  The user also has these preferences: ${preferences}, which includes specified genres. 
  
  You must **always include these specific songs**: ${songNames
    .map((song) => `"${song.name}" by ${song.artist}`)
    .join(", ")}.
    
  You must include **multiple songs from each of these artists**: ${artistNames
    .map((artist) => artist.name)
    .join(", ")}, with a minimum of 3-5 songs per artist.
  
  To complete the playlist, please add songs from other similar artists in the same genre that fit the user’s vibe, preferences, and specified songs and artists. 

  The playlist should align with the overall mood and preferences, and it must contain at least 20 songs in total.
  
  Please return the playlist as a JSON object called 'playlist'. Each entry should contain both the song name and the artist name. Make sure to include all specified songs and artists, and ensure their presence dominates the playlist.
  Please don't include the backticks and json text in the beginning, and the 3 backticks in the end.
  `;

    try {
      const result = await model.generateContent(prompt);
      const response = await result.response;

      const text = await response.text();

      const parsed = JSON.parse(text);

      setGeneratedSongs(parsed.playlist);
      setLoading(true);
      console.log("Songs: ", generatedSongs);
      if (loading == false) {
        setGenerated(true);
      } else {
        setGenerated(false);
      }
      createPlaylistAndAddTracks(token, userId, generatedSongs);
    } catch (error) {
      console.log(generatedSongs);
      console.error("Error generating playlist:", error);
    } finally {
      setLoading(false);
    }
  }

  async function oldGenerate() {
    setLoading(true);
    const prompt = `
  Generate a playlist of songs based on the user’s input. 
  The user is looking for this vibe: ${vibe}, which reflects the overall mood they want. 
  The user also has these preferences: ${preferences}, which includes specified genres. 
  
  You must **always include these specific songs**: ${songNames
    .map((song) => `"${song.name}" by ${song.artist}`)
    .join(", ")}.
    
  You must include **multiple songs from each of these artists**: ${artistNames
    .map((artist) => artist.name)
    .join(", ")}, with a minimum of 3-5 songs per artist.
  
  To complete the playlist, please add songs from other similar artists in the same genre that fit the user’s vibe, preferences, and specified songs and artists. 

  The playlist should align with the overall mood and preferences, and it must contain at least 20 songs in total.
  
  Please return the playlist as a JSON object called 'playlist'. Each entry should contain both the song name and the artist name. Make sure to include all specified songs and artists, and ensure their presence dominates the playlist.
  Please don't include the backticks and json text in the beginning, and the 3 backticks in the end.
  `;
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    console.log(JSON.parse(text));
    setGeneratedSongs(JSON.parse(text));
    setLoading(false);
    console.log(generatedSongs);
  }

  return (
    <>
      {generated == false ? (
        <div className="generateContainer">
          {error == true ? (
            <div className="error">
              <p>
                Log in expired! Please log in again at{" "}
                <a href="/">playlisty.carlahau.com</a>
              </p>
            </div>
          ) : (
            <></>
          )}
          {artistSearchBox ? (
            <div className="artistSearchContainer">
              <div className="artistSearchBox">
                <form onSubmit={searchArtists}>
                  <input
                    type="text"
                    onChange={(e) => setSearchKey(e.target.value)}
                  />
                  <button type={"submit"}>Search</button>
                  <div
                    onClick={() => setArtistSearchBox(false)}
                    className="closeBtn"
                  >
                    <Close fontSize="small" />
                  </div>
                </form>
                <div className="results">
                  {artists.map((artist) => (
                    <div
                      onClick={() =>
                        appendArtists(artist.name, artist.images[0].url)
                      }
                      className="result"
                      key={artist.id}
                    >
                      {artist.images.length ? (
                        <img src={artist.images[0].url} alt="" />
                      ) : (
                        <div>No Image</div>
                      )}
                      <p>{artist.name}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <></>
          )}
          {songSearchBox ? (
            <div className="artistSearchContainer">
              <div className="artistSearchBox">
                <form onSubmit={searchSongs}>
                  <input
                    type="text"
                    onChange={(e) => setSearchKey(e.target.value)}
                  />
                  <button type={"submit"}>Search</button>
                  <div
                    onClick={() => setSongSearchBox(false)}
                    className="closeBtn"
                  >
                    <Close fontSize="small" />
                  </div>
                </form>
                <div className="results">
                  {songs.map((song) => (
                    <div
                      onClick={() =>
                        appendSongs(
                          song.name,
                          song.album.artists[0].name,
                          song.album.images[0].url
                        )
                      }
                      className="songResult"
                      key={song.id}
                    >
                      <img src={song.album.images[0].url} />
                      <div className="songDetails">
                        <p className="songName">{song.name}</p>
                        <p className="songArtist">
                          {song.album.artists[0].name}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <></>
          )}
          <div className="generateHeader">
            <AutoAwesome fontSize="large" />
            <h1>Generate Playlist</h1>
          </div>
          <div className="generateForm">
            <form>
              <label>
                Choose your vibe, tweak your preferences, and let Playlisty work
                its magic!
              </label>
              <textarea
                value={vibe}
                onChange={(e) => setVibe(e.target.value)}
                style={{ fontSize: "20px" }}
                placeholder="What’s Your Vibe Today? What’s the occasion?"
              ></textarea>
              <div className="preferences">
                <a onClick={() => setSongSearchBox(true)}>
                  <p>Add Specific Songs</p>
                  <AddBoxOutlinedIcon className="addSign" fontSize="medium" />
                </a>
                <a onClick={() => setArtistSearchBox(true)}>
                  <p>Add Specific Artists</p>
                  <AddBoxOutlinedIcon className="addSign" fontSize="medium" />
                </a>
                <textarea
                  value={preferences}
                  onChange={(e) => setPreferences(e.target.value)}
                  style={{ fontSize: "20px" }}
                  placeholder="Specify genres or other preferences.."
                ></textarea>
              </div>
              <div className="preferredArtists">
                {songNames.map((songName, key) => (
                  <>
                    <div key={key} className="preferredSong">
                      <img src={songName.image} />
                      <div className="preferredSongDetails">
                        <p className="preferredSongName">{songName.name}</p>
                        <p className="preferredSongArtist">{songName.artist}</p>
                      </div>
                      <div
                        onClick={() =>
                          deleteSongs(
                            songName.name,
                            songName.artist,
                            songName.image
                          )
                        }
                        className="deleteArtistPreference"
                      >
                        <Close />
                      </div>
                    </div>
                  </>
                ))}
              </div>
              <div className="preferredArtists">
                {artistNames.map((artistName, key) => (
                  <>
                    <div key={key} className="preferredArtist">
                      <img src={artistName.image} />
                      <p>{artistName.name}</p>
                      <div
                        onClick={() =>
                          deleteArtist(artistName.name, artistName.image)
                        }
                        className="deleteArtistPreference"
                      >
                        <Close />
                      </div>
                    </div>
                  </>
                ))}
              </div>
              <input
                onClick={generate}
                className="generateButton"
                type="button"
                value="Generate Now!"
              ></input>
            </form>
            {loading == true ? (
              <div className="loadingMsg">
                <HourglassEmptyIcon fontSize="large" />
                <p>Generating Now! This might take a minute.</p>
              </div>
            ) : (
              <></>
            )}
          </div>
        </div>
      ) : (
        <>
          <GeneratedPlaylist name={vibe} songs={generatedSongs} />
        </>
      )}
    </>
  );
}
