import React from "react";
import "../styles/Playlists.css";
import { QueueMusic } from "@mui/icons-material";
import { useState } from "react";

export default function Playlists() {
  const [userPlaylists, setUserPlaylists] = useState([]);
  const [playlistImages, setPlaylistImages] = useState([]);
  const [playlistNames, setPlaylistNames] = useState([]);
  const [playlistInfo, setPlaylistInfo] = useState([]);

  async function getPlaylistsByDescription() {
    let token = window.localStorage.getItem("token");
    const spotifyApi = new SpotifyWebApi();
    spotifyApi.setAccessToken(token);

    try {
      const data = await spotifyApi.getUserPlaylists({
        query: "Generated by Carla Hau's Playlisty. ",
      });

      const playlists = data.items;
      const images = playlists.map((item) => item.images[0].url);
      const names = playlists.map((item) => item.name);
      const playlistInfo = playlists.map((item) => ({
        name: item.name,
        images: item.images[0].url,
      }));

      console.log(playlistInfo);
      setPlaylistImages(images);
      setPlaylistNames(names);
      setPlaylistInfo(playlistInfo);
    } catch (error) {
      console.error("Error fetching playlists:", error);
    }
  }

  getPlaylistsByDescription();

  return (
    <div className="playlistsContainer">
      <div className="generateHeader">
        <QueueMusic fontSize="large" />
        <h1>My Playlists</h1>
      </div>
      <div className="playlistContainer">
        <div className="playlists">
          {playlistInfo.map((data) => (
            <div>
              <img src={data.images} />
              <p>{data.name}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
